name = "MCTS"
uuid = "e12ccd36-dcad-5f33-8774-9175229e7b33"
repo = "https://github.com/JuliaPOMDP/MCTS.jl"
version = "0.5.3"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Colors = "0.9, 0.10, 0.11, 0.12"
D3Trees = "0.3"
POMDPLinter = "0.1"
POMDPTools = "0.1"
POMDPs = "0.9"
ProgressMeter = "1"
julia = "1"

[extras]
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["POMDPModels", "NBInclude", "Test"]
